version: '3.8'

services:
  gradio:
    image: gradio_client
    container_name: gradio
    ports:
      - "7860:7860"
    volumes:
      - shared_logs:/app/shared_logs/logs
    build: 
      context: ./frontend
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - EXA_API_KEY=${EXA_API_KEY}
      - JINA_API_KEY=${JINA_API_KEY}
      - GUARDRAILS_API_KEY=${GUARDRAILS_API_KEY}
    networks:
      - app-network
    depends_on:
      - fastapiserver

  fastapiserver:
    image: backend
    container_name: fastapiserver
    ports:
      - "8001:8001"  # Added port mapping
    volumes:
      - shared_logs:/app/shared_logs/logs
    environment:
      - JINA_API_KEY=${JINA_API_KEY}
      - GUARDRAILS_API_KEY=${GUARDRAILS_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    build:
      context: ./backend
      args:
        GUARDRAILS_API_KEY: ${GUARDRAILS_API_KEY}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        JINA_API_KEY: ${JINA_API_KEY}
    networks:
      - app-network  # Added to shared network

volumes:
  shared_logs:

networks:
  app-network:
    driver: bridge
